version: '3.3'
services:
    filebrowser:
        image: filebrowser/filebrowser:latest
        container_name: filebrowser
        user: 0:0
        ports:
            - 8086:80
        volumes:
            - /:/srv
            - /dockers/compose/filebrowser/filebrowser.db:/database.db
        restart: unless-stopped
        environment:
            - TZ=Europe/Lisbon
        security_opt:
            - no-new-privileges:true